# Generated by Django 5.2.11 on 2026-02-06 01:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('order_index', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caso de Teste',
                'verbose_name_plural': 'Casos de Testes',
                'ordering': ['test_plan', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='GMUDVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gmud_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versão GMUD',
                'verbose_name_plural': 'Versões GMUD',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('FALHOU', 'Falhou'), ('NAO_APLICA', 'Não se Aplica')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_executions', to=settings.AUTH_USER_MODEL)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api.testcase')),
            ],
            options={
                'verbose_name': 'Execução de Teste',
                'verbose_name_plural': 'Execução de Testes',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='evidences/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='api.testexecution')),
            ],
            options={
                'verbose_name': 'Evidência',
                'verbose_name_plural': 'Evidências',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('division', models.CharField(max_length=100)),
                ('system', models.CharField(max_length=100)),
                ('environment', models.CharField(max_length=50)),
                ('validation_type', models.CharField(choices=[('FUNCIONAL', 'Funcional'), ('REGRESSAO', 'Regressão'), ('INTEGRACAO', 'Integração'), ('PERFORMANCE', 'Performance'), ('SEGURANCA', 'Segurança')], max_length=50)),
                ('status', models.CharField(choices=[('AGUARDANDO_TESTE', 'Aguardando Teste'), ('EM_PROGRESSO', 'Em Progresso'), ('CONCLUIDO', 'Concluído'), ('FALHOU', 'Falhou')], default='AGUARDANDO TESTE', max_length=30)),
                ('access_key', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_test_plan', to=settings.AUTH_USER_MODEL)),
                ('gmud_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_plan', to='api.gmudversion')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_test_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Teste',
                'verbose_name_plural': 'Plano de Teste',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='api.testplan'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('AUDITOR', 'Auditor'), ('TESTADOR', 'Testador')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('entity', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='api_auditlo_user_id_b0c441_idx'), models.Index(fields=['created_at'], name='api_auditlo_created_ec4a64_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['-executed_by'], name='api_testexe_execute_7fc4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='testplan',
            index=models.Index(fields=['-status'], name='api_testpla_status_4552d9_idx'),
        ),
        migrations.AddIndex(
            model_name='testplan',
            index=models.Index(fields=['created_by'], name='api_testpla_created_22b685_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('test_plan', 'order_index')},
        ),
    ]
