# Generated by Django 6.0.2 on 2026-02-19 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='testexecution',
            name='api_testexe_execute_7fc4ac_idx',
        ),
        migrations.AlterField(
            model_name='testplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_test_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='gmud_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_plans', to='api.gmudversion'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_test_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_TESTE', 'Aguardando Teste'), ('EM_PROGRESSO', 'Em Progresso'), ('CONCLUIDO', 'Concluído'), ('FALHOU', 'Falhou')], default='AGUARDANDO_TESTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['executed_by'], name='api_testexe_execute_a981af_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['executed_at'], name='api_testexe_execute_042878_idx'),
        ),
    ]
