# Generated by Django 6.0.2 on 2026-02-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_testexecution_api_testexe_execute_7fc4ac_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testexecution',
            options={'ordering': ['-executed_at'], 'verbose_name': 'Execução de Teste', 'verbose_name_plural': 'Execuções de Teste'},
        ),
        migrations.AddField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('OK', 'Ok'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20),
        ),
    ]
