# Generated by Django 6.0.2 on 2026-02-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_testexecution_options_testcase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='environment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
