# Generated by Django 6.0.2 on 2026-02-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_testplan_environment_alter_testplan_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIGURADA', 'Configurada'), ('AGUARDANDO_TESTE', 'Aguardando Teste'), ('EM_PROGRESSO', 'Em Progresso'), ('CONCLUIDO', 'Concluído'), ('FALHOU', 'Falhou')], default='RASCUNHO', max_length=30),
        ),
    ]
