# Generated by Django 6.0.2 on 2026-02-25 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_testplan_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='responsible',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_test_plans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
