# Generated by Django 6.0.2 on 2026-02-26 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_testplan_responsible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em andamento'), ('FAILED', 'Reprovada'), ('APPROVED', 'Aprovada'), ('ARCHIVED', 'Arquivada')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='testexecution',
            options={'ordering': ['-executed_at']},
        ),
        migrations.RemoveIndex(
            model_name='testexecution',
            name='api_testexe_execute_a981af_idx',
        ),
        migrations.RemoveIndex(
            model_name='testexecution',
            name='api_testexe_execute_042878_idx',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='status',
        ),
        migrations.AlterField(
            model_name='testplan',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIGURADA', 'Configurada'), ('PRONTA_PARA_TESTE', 'Pronta para Teste')], default='RASCUNHO', max_length=30),
        ),
        migrations.AddField(
            model_name='validationsession',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validation_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='validationsession',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.testplan'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api.validationsession'),
        ),
        migrations.AddIndex(
            model_name='validationsession',
            index=models.Index(fields=['test_plan'], name='api_validat_test_pl_08c5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='validationsession',
            index=models.Index(fields=['status'], name='api_validat_status_525994_idx'),
        ),
        migrations.AddConstraint(
            model_name='validationsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('test_plan',), name='unique_active_session_per_plan'),
        ),
    ]
