# Generated by Django 6.0.2 on 2026-02-26 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_validationsession_alter_testexecution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api.validationsession'),
        ),
    ]
