# Generated by Django 5.2.11 on 2026-02-27 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_testexecution_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='comment',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='testexecution',
            constraint=models.UniqueConstraint(fields=('session', 'test_case'), name='unique_execution_per_test_case_per_session'),
        ),
    ]
