# Generated by Django 5.2.11 on 2026-03-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_testexecution_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationsession',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='validationsession',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
