# Generated by Django 5.2.11 on 2026-03-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_validationsession_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexecution',
            name='evidence',
        ),
    ]
