# Generated by Django 5.2.11 on 2026-03-12 00:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_testexecution_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='validationsession',
            name='unique_active_session_per_plan',
        ),
        migrations.AddConstraint(
            model_name='validationsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('test_plan',), name='unique_user_active_session'),
        ),
    ]
