# Generated by Django 6.0.2 on 2026-03-13 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_validationsession_unique_active_session_per_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='validationsession',
            name='unique_user_active_session',
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('OK', 'OK'), ('FALHOU', 'Falhou'), ('NAO_APLICA', 'Não se Aplica')], default='PENDENTE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='validationsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('test_plan',), name='unique_user_active_session'),
        ),
    ]
