# Generated by Django 5.2.11 on 2026-03-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_validationsession_unique_active_session_per_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('OK', 'OK'), ('FALHOU', 'Falhou'), ('NAO_APLICA', 'Não se Aplica')], default='PENDENTE', max_length=20),
        ),
    ]
