# Generated by Django 6.0.2 on 2026-04-01 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_validationsession_unique_user_active_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationAccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('setor', models.CharField(max_length=100)),
                ('max_uses', models.IntegerField(default=1)),
                ('used_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='testexecution',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='testexecution',
            name='unique_execution_per_test_case_per_session',
        ),
        migrations.RemoveConstraint(
            model_name='validationsession',
            name='unique_user_active_session',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='access_key',
        ),
        migrations.AddField(
            model_name='testplan',
            name='setores',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='validationsession',
            name='setor',
            field=models.CharField(default='DEFAULT', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Em elaboração'), ('READY', 'Pronto para validação'), ('IN_PROGRESS', 'Em validação'), ('VALIDATED_IN_PARTS', 'Validado em partes'), ('VALIDATED', 'Validado')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='validationsession',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluída'), ('ARCHIVED', 'Arquivada')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AddField(
            model_name='validationaccesskey',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to='api.testplan'),
        ),
    ]
