# Generated by Django 6.0.2 on 2026-04-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_validationaccesskey_alter_testexecution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='setor',
            field=models.CharField(default='GERAL', max_length=100),
            preserve_default=False,
        ),
    ]
