# Generated by Django 6.0.2 on 2026-04-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_testcase_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='is_multivalidation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='validationaccesskey',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
